image: node:10.0.0

pipelines:
  default:
    - step:
        name: Build & Test
        script:
          - npm install --global npm@latest               #Update npm to latest stable version
          - cd examples/backbone_marionette               #Set working directory
          - npm install --global http-server              #Installs the http-server module
          - npm ci                                        #Installs a project with a clean state
          - zipFileName="todomvc"-$BITBUCKET_BUILD_NUMBER #Names the zip file
          - python -c "import shutil;shutil.make_archive('$zipFileName','zip',root_dir='.', base_dir='.')" #Zips folder
          - sh ./tests/start-server.sh                    #Starts a http-server in the background
          - npm test                                      #Runs the tests indicated in the package.json file
        artifacts:                                        #Defines the artifacts to be passed to each future step
          - examples/backbone_marionette/*.zip