# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        name: Build & Test
        script:
          - cd examples/backbone_marionette #Set working directory
          - npm ci #Installs a project with a clean state
          - zipFileName="todomvc"-$BITBUCKET_BUILD_NUMBER #Names the zip file
          - python -c "import shutil;shutil.make_archive('$zipFileName','zip',root_dir='.', base_dir='.')" #Zips folder
          - sh ./tests/start-server.sh #Starts a http-server in the background
          - npm test #Runs the tests indicated in the package.json file
        artifacts: # defining the artifacts to be passed to each future step.
          - examples/backbone_marionette/*.zip